version: '2'

services:
  php:
    build: ./docker/php
    environment:
      - APACHE_DOCUMENT_ROOT=/php/public
      - TZ=Asia/Tokyo
    ports:
      - "8051:80"
    volumes:
      - .:/php
    depends_on:
      - mysql
  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phpapptest
      - MYSQL_DATABASE=editmaster
    volumes:
      - ./docker/mysql:/docker
    tty: true
