apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9093
    targetPort: 9093
    nodePort: 30193
  selector:
    app: alertmanager
