apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: php
        image: gcr.io/editmasterapi/php:latest
        command: ["/bin/bash"]
        args:
        - "-c"
        - "php artisan migrate --force"
        env:
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: DB_PASSWORD
      restartPolicy: Never
