apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: php
        image: gcr.io/editmasterapi/php:latest
        command: ["/bin/bash"]
        args:
        - "-c"
        - "php artisan migrate --force"
        env:
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "editmaster"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_password
      restartPolicy: Never
