apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    app: php
  ports:
    - name: http
      port: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: gcr.io/editmasterapi/php:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "Laravel"
        - name: APP_ENV
          value: "production"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: app_key
        - name: APP_DEBUG
          value: "false"
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "editmaster"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_password
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: youtube_api_key
